title: DevOps Training Session password=naveen123
description: GitHub, Jenkins, Testing, Packages, Deployment, Automation
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
